title: Kshitij Dahal
logo: kd-modified.png
description: |
  Room 410, 777 E University Dr, Tempe, AZ 85287, USA.
  
  PhD student at Arizona State University.
  Editorial Advisory Board, Regional Environmental Change.
show_downloads: false
theme: jekyll-theme-minimal
